version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
        - run: npm install
  unit-test:
    steps:
      - checkout
      - node/with-cache:
          - run: npm test
  lint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          - run: npm run linter
workflows:
    build-and-test:
      jobs:
        - build
        - lint:
            requires:
              - build
        - unit-test:
            requires:
              - build